[book]
authors = ["icerdesign"]
language = "en"
multilingual = false
src = "src"
title = "Pawket Security White Paper"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true


[output.html.redirect]
"/Chain-Chia.html" = "../chia/encryption.html"
